# These are supported funding model platforms

github: [bjoerrrn] # Replace with your GitHub username
# patreon: [user_name]
# open_collective: [user_name]
# ko_fi: [user_name]
# tidelift: [community-id]
# community_bridge: [project-name]
# liberapay: [user_name]
# issuehunt: [user_name]
# buy_me_a_coffee: [user_name]
# custom: ['https://www.paypal.me/yourusername'] # Replace with your direct link
